### ISSUE TITLE
State can be different from X0 value, eg 204 = defrosting

### ISSUE THREAD

**Issue by barryvdh** [wefabricate/wh-python#13]
This checks the 180, 200 etc values:

https://github.com/wefabricate/wh-python/blob/4fa5f0ba09c60871624836561a4851e2b48facfd/weheat/abstractions/heat_pump.py#L239-L255

But currently my state is 204

```
 {
        "heatPumpId": "746f..d75",
        "timestamp": "2024-11-18T08:00:34.557Z",
        "state": 204,
        "rpmCtrl": 6,
        "error": null,
..
}
```

The portal shows this as defrosting 
<img width="180" alt="image" src="https://github.com/user-attachments/assets/7d89d194-86bf-457a-a7d5-85631b36cc01">

Should the check be altered to >200 and <210 ?

**Comment by erikgeurts** [comment]
Yes, I've observed the same thing, during defrost cycles, the API has been returning various status codes in short sequence:

> 202, 203, 204, 205, 206

I haven't personally seen code 90 begin returned, even though the documentation indicates that 90 means defrost.

**Comment by jesperraemaekers** [comment]
This will be resolved next release. Thanks!

**Comment by erikgeurts** [comment]
Could you perhaps be a little bit more specific?
- Do you mean to say that after the next release a defrost will only return 90?
- Next release of what?

**Comment by barryvdh** [comment]
Next release of this package will mark 200-209 as defrost. See https://github.com/wefabricate/wh-python/pull/14

**Comment by jesperraemaekers** [comment]
After a the next release of this package the problem is solved for users of this package.
After the next release of HA the problem is solved for HA users as this is an simple dependency upgrade for HA.

All possible defrosts states, which is 200 to 240, are now translated to a defrost state.

**Comment by erikgeurts** [comment]
I'm sorry, but this is confusing. Your own code say [defrost is status code 90](https://github.com/wefabricate/wh-python/blob/main/weheat/models/heat_pump_status_enum.py#L26). Does this change mean that in the near future the API may return any value between 200 and 240 instead to indicate the heat pump is in a defrost state?

**Comment by jesperraemaekers** [comment]
the API likely hasn't returned 90 since beginning of 2024 when this was changed.  So 200-240 is currently what is returned.
The docs are outdated, I'll have a look at updating them when it is less busy.

**Comment by erikgeurts** [comment]
Thanks for clarifying. I actually already noticed that a defrost never returns 90 in the API. Good to know that soon I should expect 200 to 240 to mean defrost.

**Comment by bvanelli** [comment]
@jesperraemaekers would it be possible to generate a new release? I guess it would solve https://github.com/home-assistant/core/issues/131057 and contribute to https://github.com/home-assistant/core/issues/99218

**Comment by jesperraemaekers** [comment]
@bvanelli can i reach you on discord somewhere? There is actually an issue with pydantic.

**Comment by bvanelli** [comment]
> @bvanelli can i reach you on discord somewhere? There is actually an issue with pydantic.

Sure, but I can only respond outside business hours, handle is `enygma_.`

**Comment by barryvdh** [comment]
Same issue for cooling: https://github.com/wefabricate/wh-python/pull/36
Maybe also for other states.
